# Generated by Django 5.0.6 on 2024-06-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '1. Employees'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='years_at_comapany',
            new_name='years_at_company',
        ),
    ]
